### ISSUE TITLE
direct_mail 6.0.0-dev Error

### ISSUE THREAD

**Issue by chrcan** [jokumer/direct_mail#2] opened 2019-11-27 16:07 UTC
With the new Version of direct_mail 6.0.0-dev Error i have errors in Frontend and in the Backend Tools in Typo 9.5.11

Frontend Error:

(1/1) #1294585866 InvalidArgumentException
No class named DirectMailTeam\DirectMail\Hooks\JumpurlController

Backend Error:

(1/1) Error
Class 'DirectMailTeam\DirectMail\Module\Dmail' not found

(1/1) Error
Class 'DirectMailTeam\DirectMail\Module\RecipientList' not found

(1/1) Error
Class 'DirectMailTeam\DirectMail\Module\Statistics' not found

1/1) Error
Class 'DirectMailTeam\DirectMail\Module\MailerEngine' not found

(1/1) Error
Class 'DirectMailTeam\DirectMail\Module\Configuration' not found

**Comment by jokumer** [comment] 2019-11-30 16:00
@chrcan I did try and can not reproduce with classic mode (without composer).
Seems like your installed version is broken due to any unwanted mistake.

Could you check your installation?
* Is extension installed with correct name 'direct_mail'?
* Does folder Classes with subfolder and files exist?
Try any of followed:
* Uninstall/install extension.
* Remove folder `typo3temp`.
* Check or compare folder and files in your TYPO3 installation with git clone of commit 98046ee2fb32d0ba6ff1120e1fe57e76877ab790 from branch TYPO3_9

**Comment by villamarianne** [comment] 2019-11-30 23:30
This happens most likely due to missing autoloading in composer mode.
Additionaly the composer.json needs some adjustments.

- Clone the TYPO3_9 branch to your local extension directory (/packages/direct_mail in my case)
- Update require section in composer.json
```json
"require": {
    "typo3/cms-core": "^9.5",
    "friendsoftypo3/jumpurl": "^7.8",
    "friendsoftypo3/tt-address": "^5.0",
    "friendsoftypo3/rdct": "^1.0"
},
```
- install it with `composer req directmailteam/direct-mail @dev`

More information about local extension in composer mode can be found [here](https://docs.typo3.org/m/typo3/guide-installation/master/en-us/MigrateToComposer/BestPractices.html).

Hope this helps.

**Comment by jokumer** [comment] 2019-12-01 10:41
@chrcan can you make a test?
Please change line 37 in composer.json and removing vendor name.
from
```
"replace": {
    "directmailteam/direct-mail": "self.version",
    "typo3-ter/direct-mail": "self.version"
  }
```
to 
```
"replace": {
    "direct-mail": "self.version",
    "typo3-ter/direct-mail": "self.version"
  }
```
This was the first change for TYPO3 9.5 from april 2019 (7ee0f30).
You are maybe faster to test with your environment. I do not have started any composer installation yet.
Thanks in advance.

**Comment by chrcan** [comment] 2019-12-01 12:04
have made all the changes ...

I created a folder Source / Extension / direct-mail there I unpacked the direct_mail-TYPO3_9.zip and renamed it to direct-mail.
In my composer.json I added under repositoris {"type": "path", "url": "./Source/Extensions/direct-mail"}. Unfortunately I can not install direct-mail on this way.

composer req directmailteam / direct-mail @dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - directmailteam/direct-mail v5.1.1 requires typo3/cms-core >=7.6,<8.0 -> no matching package found.
    - directmailteam/direct-mail dev-release/5.2.0 requires typo3/cms-core >=7.6,<8.0 -> no matching package found.
    - directmailteam/direct-mail dev-github_78 requires typo3/cms-core >=7.6,<8.0 -> no matching package found.
    - directmailteam/direct-mail dev-feature/github_64 requires typo3/cms-core >=7.6,<8.0 -> no matching package found.
    - directmailteam/direct-mail dev-feature/github-68 requires typo3/cms-core >=7.6,<8.0 -> no matching package found.
    - directmailteam/direct-mail 5.2.0 requires typo3/cms-core >=7.6,<8.0 -> no matching package found.
    - directmailteam/direct-mail 5.1.0 requires typo3/cms-core >=7.6,<8.0 -> no matching package found.
    - directmailteam/direct-mail 5.0.1 requires typo3/cms-core >=7.6,<8.0 -> no matching package found.
    - directmailteam/direct-mail 5.0 requires typo3/cms-core >=7.6.2,<8.0 -> no matching package found.
    - typo3/cms-core v8.7.8 requires php >=7.0.0 <=7.1.99 -> your PHP version (7.3.11) overridden by "config.platform.php" version (7.2) does not satisfy that requirement.
    - typo3/cms-core v8.7.7 requires php >=7.0.0 <=7.1.99 -> your PHP version (7.3.11) overridden by "config.platform.php" version (7.2) does not satisfy that requirement.
    - Conclusion: don't install directmailteam/direct-mail 5.2.3
    - Conclusion: don't install directmailteam/direct-mail 5.2.2
    - Conclusion: don't install directmailteam/direct-mail 5.2.1
    - Conclusion: don't install directmailteam/direct-mail dev-develop
    - Conclusion: don't install directmailteam/direct-mail dev-documentation-draft
    - Conclusion: don't install directmailteam/direct-mail dev-feature/github_159
    - Conclusion: remove doctrine/dbal v2.10.0
    - Installation request for directmailteam/direct-mail @dev -> satisfiable by directmailteam/direct-mail[5.0, 5.0.1, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.2.3, dev-develop, dev-documentation-draft, dev-feature/github-68, dev-feature/github_159, dev-feature/github_160, dev-feature/github_64, dev-github_78, dev-release/5.2.0, v5.1.1].
    - Conclusion: don't install doctrine/dbal v2.10.0
    - directmailteam/direct-mail dev-feature/github_160 requires typo3/cms-core >=7.6,<9.0 -> satisfiable by typo3/cms-core[v8.7.10, v8.7.11, v8.7.12, v8.7.13, v8.7.14, v8.7.15, v8.7.16, v8.7.17, v8.7.18, v8.7.19, v8.7.20, v8.7.21, v8.7.22, v8.7.23, v8.7.24, v8.7.25, v8.7.26, v8.7.27, v8.7.28, v8.7.29, v8.7.7, v8.7.8, v8.7.9].
    - typo3/cms-core v8.7.10 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.11 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.12 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.13 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.14 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.15 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.16 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.17 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.18 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.19 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.20 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.21 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.22 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.23 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.24 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.25 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.26 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.27 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.28 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.29 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - typo3/cms-core v8.7.9 requires doctrine/dbal ~2.5.4 -> satisfiable by doctrine/dbal[v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - Can only install one of: doctrine/dbal[v2.5.10, v2.10.0].
    - Can only install one of: doctrine/dbal[v2.5.11, v2.10.0].
    - Can only install one of: doctrine/dbal[v2.5.12, v2.10.0].
    - Can only install one of: doctrine/dbal[v2.5.13, v2.10.0].
    - Can only install one of: doctrine/dbal[v2.5.4, v2.10.0].
    - Can only install one of: doctrine/dbal[v2.5.5, v2.10.0].
    - Can only install one of: doctrine/dbal[v2.5.6, v2.10.0].
    - Can only install one of: doctrine/dbal[v2.5.7, v2.10.0].
    - Can only install one of: doctrine/dbal[v2.5.8, v2.10.0].
    - Can only install one of: doctrine/dbal[v2.5.9, v2.10.0].
    - Installation request for doctrine/dbal (locked at v2.10.0) -> satisfiable by doctrine/dbal[v2.10.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by chrcan** [comment] 2019-12-01 12:15
ok i made all changes.
now I have a error:

(1/1) #1460976566 InvalidArgumentException

[module-DirectMailNavFrame] The option "source" is required and must not be empty

**Comment by jokumer** [comment] 2019-12-01 13:02
Fine, thx for test and fast reply. That means you could solve the originally described error.
May I ask you to send a PR for composer change, which solves the originally described error?
This way you can even more contribute and help to improve and push direct_mail to be TYPO3 9.5 compatible.
The next error you got, may come from another incompatibility.
If it is not composer vendorname related (as I think), this should become a new issue.

**Comment by chrcan** [comment] 2019-12-01 13:22
Now I have the change the composer.json again on: 
"replace": {
    "directmailteam / direct-mail": "self.version",
    "typo3-ter / direct-mail": "self.version"
  },
only just to test what happens now with the korrekt installation method ...
Finaly i have no error in the FE and the BE.
The next step ist testing send a newsletter.

**Comment by jokumer** [comment] 2019-12-01 13:31
There will be still a lot of different errors with this extension in TYPO3 v9.5
We need to collect them in different issue tickets and solves them separately.

**Comment by villamarianne** [comment] 2019-12-02 10:20
`"directmailteam/direct-mail": "self.version",` works find for me

**Comment by jokumer** [comment] 2019-12-02 10:26
I will close this issue then. The Change/PullRequest is for issue #3 only. Issue #4 does not exist yet.

**Closed as completed by jokumer** 2019-12-02 10:26 UTC
