### ISSUE TITLE
Swift_RfcComplianceException

### ISSUE THREAD

**Issue by chrcan** [jokumer/direct_mail#7] opened 2019-12-03 13:23 UTC
If I send directly from the mailing list of direct-mail I get this error:

(1/1) Swift_RfcComplianceException
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

**Comment by jokumer** [comment] 2020-01-07 21:38
Duplicate of #5

**Closed as completed by jokumer** 2020-01-07 21:38 UTC
